name: Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.9
        with:
          version: 8.7
      - run: raco pkg install --auto https://github.com/michaelballantyne/syntax-spec.git
      - run: raco pkg install --auto
      - run: raco setup hosted-minikanren
      - run: raco test -c hosted-minikanren

  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.6
        with:
          version: 8.7
      - run: raco pkg install --auto https://github.com/michaelballantyne/syntax-spec.git
      - run: raco pkg install --auto
      - run: raco setup hosted-minikanren
      - run: raco test private/compile/*.rkt
